version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm ci --ignore-scripts  # Install dependencies without executing pre/post install scripts

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - 'build/**/*'
    - 'package.json'
    - 'appspec.yml'
    - 'scripts/**/*'
